// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Account struct {
	ID           int64
	Username     string
	PasswordHash string
	Role         int64
}

type BlogPost struct {
	ID        int64
	Title     string
	Content   string
	CreatedAt string
	Status    string
	AccountID int64
}
