// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type AdminAccount struct {
	ID           int64
	Email        string
	PasswordHash string
}

type Employer struct {
	ID   int64
	Name string
}

type EmployerAccount struct {
	ID           int64
	Email        string
	PasswordHash string
	EmployerID   int64
}

type JobPost struct {
	ID         int64
	Title      string
	Content    string
	CreatedAt  string
	Status     string
	EmployerID int64
}
