name: Build Frontend

on:
  workflow_call:

jobs:
  nextjs-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4
      - name: Use npm
        uses: actions/setup-node@v4

      - name: Build frontend
        run: |
          npm install
          npm run build
      - name: Upload frontend files
        uses: actions/upload-artifact@v4
        with:
          name: frontend-static-files
          path: ui/out