name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 2'
  workflow_dispatch:

jobs:
  nextjs-build:
    uses: ./.github/workflows/frontend-build.yaml
  go-build:
    needs: [nextjs-build]
    uses: ./.github/workflows/go-build.yaml
  go-lint:
    uses: ./.github/workflows/go-lint.yaml
  go-vet:
    uses: ./.github/workflows/go-vet.yaml
  go-unit-test:
    uses: ./.github/workflows/go-unit-tests.yaml
  sqlc-diff:
    uses: ./.github/workflows/sqlc-diff.yaml
  sqlc-vet:
    uses: ./.github/workflows/sqlc-vet.yaml
  rock-build:
    needs: [go-build, go-unit-test, go-vet, go-lint]
    uses: ./.github/workflows/rock-build.yaml
  rock-publish:
    if: github.ref_name == 'main'
    needs: [rock-build]
    uses: ./.github/workflows/rock-publish.yaml
