name: SQLC Diff

on:
  workflow_call:

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.27.0'
    - run: sqlc diff
